# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T02:46:11+00:00

from __future__ import annotations

from enum import Enum
from typing import List, Optional

from pydantic import BaseModel, Field


class GoogleProtobufEmpty(BaseModel):
    pass


class GoogleSecuritySafebrowsingV4Checksum(BaseModel):
    sha256: Optional[str] = Field(
        None,
        description='The SHA256 hash of the client state; that is, of the sorted list of all hashes present in the database.',
    )


class GoogleSecuritySafebrowsingV4ClientInfo(BaseModel):
    clientId: Optional[str] = Field(
        None,
        description='A client ID that (hopefully) uniquely identifies the client implementation of the Safe Browsing API.',
    )
    clientVersion: Optional[str] = Field(
        None, description='The version of the client implementation.'
    )


class PlatformType(Enum):
    PLATFORM_TYPE_UNSPECIFIED = 'PLATFORM_TYPE_UNSPECIFIED'
    WINDOWS = 'WINDOWS'
    LINUX = 'LINUX'
    ANDROID = 'ANDROID'
    OSX = 'OSX'
    IOS = 'IOS'
    ANY_PLATFORM = 'ANY_PLATFORM'
    ALL_PLATFORMS = 'ALL_PLATFORMS'
    CHROME = 'CHROME'


class ThreatEntryType(Enum):
    THREAT_ENTRY_TYPE_UNSPECIFIED = 'THREAT_ENTRY_TYPE_UNSPECIFIED'
    URL = 'URL'
    EXECUTABLE = 'EXECUTABLE'
    IP_RANGE = 'IP_RANGE'
    CHROME_EXTENSION = 'CHROME_EXTENSION'
    FILENAME = 'FILENAME'
    CERT = 'CERT'


class ThreatType(Enum):
    THREAT_TYPE_UNSPECIFIED = 'THREAT_TYPE_UNSPECIFIED'
    MALWARE = 'MALWARE'
    SOCIAL_ENGINEERING = 'SOCIAL_ENGINEERING'
    UNWANTED_SOFTWARE = 'UNWANTED_SOFTWARE'
    POTENTIALLY_HARMFUL_APPLICATION = 'POTENTIALLY_HARMFUL_APPLICATION'
    SOCIAL_ENGINEERING_INTERNAL = 'SOCIAL_ENGINEERING_INTERNAL'
    API_ABUSE = 'API_ABUSE'
    MALICIOUS_BINARY = 'MALICIOUS_BINARY'
    CSD_WHITELIST = 'CSD_WHITELIST'
    CSD_DOWNLOAD_WHITELIST = 'CSD_DOWNLOAD_WHITELIST'
    CLIENT_INCIDENT = 'CLIENT_INCIDENT'
    CLIENT_INCIDENT_WHITELIST = 'CLIENT_INCIDENT_WHITELIST'
    APK_MALWARE_OFFLINE = 'APK_MALWARE_OFFLINE'
    SUBRESOURCE_FILTER = 'SUBRESOURCE_FILTER'
    SUSPICIOUS = 'SUSPICIOUS'
    TRICK_TO_BILL = 'TRICK_TO_BILL'
    HIGH_CONFIDENCE_ALLOWLIST = 'HIGH_CONFIDENCE_ALLOWLIST'
    ACCURACY_TIPS = 'ACCURACY_TIPS'


class SupportedCompression(Enum):
    COMPRESSION_TYPE_UNSPECIFIED = 'COMPRESSION_TYPE_UNSPECIFIED'
    RAW = 'RAW'
    RICE = 'RICE'


class GoogleSecuritySafebrowsingV4FetchThreatListUpdatesRequestListUpdateRequestConstraints(
    BaseModel
):
    deviceLocation: Optional[str] = Field(
        None,
        description="A client's physical location, expressed as a ISO 31166-1 alpha-2 region code.",
    )
    language: Optional[str] = Field(
        None,
        description='Requests the lists for a specific language. Expects ISO 639 alpha-2 format.',
    )
    maxDatabaseEntries: Optional[int] = Field(
        None,
        description='Sets the maximum number of entries that the client is willing to have in the local database for the specified list. This should be a power of 2 between 2**10 and 2**20. If zero, no database size limit is set.',
    )
    maxUpdateEntries: Optional[int] = Field(
        None,
        description='The maximum size in number of entries. The update will not contain more entries than this value. This should be a power of 2 between 2**10 and 2**20. If zero, no update size limit is set.',
    )
    region: Optional[str] = Field(
        None,
        description="Requests the list for a specific geographic location. If not set the server may pick that value based on the user's IP address. Expects ISO 3166-1 alpha-2 format.",
    )
    supportedCompressions: Optional[List[SupportedCompression]] = Field(
        None, description='The compression types supported by the client.'
    )


class ResponseType(Enum):
    RESPONSE_TYPE_UNSPECIFIED = 'RESPONSE_TYPE_UNSPECIFIED'
    PARTIAL_UPDATE = 'PARTIAL_UPDATE'
    FULL_UPDATE = 'FULL_UPDATE'


class GoogleSecuritySafebrowsingV4RawHashes(BaseModel):
    prefixSize: Optional[int] = Field(
        None,
        description='The number of bytes for each prefix encoded below. This field can be anywhere from 4 (shortest prefix) to 32 (full SHA256 hash).',
    )
    rawHashes: Optional[str] = Field(
        None,
        description='The hashes, in binary format, concatenated into one long string. Hashes are sorted in lexicographic order. For JSON API users, hashes are base64-encoded.',
    )


class GoogleSecuritySafebrowsingV4RawIndices(BaseModel):
    indices: Optional[List[int]] = Field(
        None,
        description='The indices to remove from a lexicographically-sorted local list.',
    )


class GoogleSecuritySafebrowsingV4RiceDeltaEncoding(BaseModel):
    encodedData: Optional[str] = Field(
        None,
        description='The encoded deltas that are encoded using the Golomb-Rice coder.',
    )
    firstValue: Optional[str] = Field(
        None,
        description="The offset of the first entry in the encoded data, or, if only a single integer was encoded, that single integer's value. If the field is empty or missing, assume zero.",
    )
    numEntries: Optional[int] = Field(
        None,
        description='The number of entries that are delta encoded in the encoded data. If only a single integer was encoded, this will be zero and the single value will be stored in `first_value`.',
    )
    riceParameter: Optional[int] = Field(
        None,
        description='The Golomb-Rice parameter, which is a number between 2 and 28. This field is missing (that is, zero) if `num_entries` is zero.',
    )


class GoogleSecuritySafebrowsingV4ThreatEntry(BaseModel):
    digest: Optional[str] = Field(
        None,
        description='The digest of an executable in SHA256 format. The API supports both binary and hex digests. For JSON requests, digests are base64-encoded.',
    )
    hash: Optional[str] = Field(
        None,
        description='A hash prefix, consisting of the most significant 4-32 bytes of a SHA256 hash. This field is in binary format. For JSON requests, hashes are base64-encoded.',
    )
    url: Optional[str] = Field(None, description='A URL.')


class GoogleSecuritySafebrowsingV4ThreatEntryMetadataMetadataEntry(BaseModel):
    key: Optional[str] = Field(
        None,
        description='The metadata entry key. For JSON requests, the key is base64-encoded.',
    )
    value: Optional[str] = Field(
        None,
        description='The metadata entry value. For JSON requests, the value is base64-encoded.',
    )


class CompressionType(Enum):
    COMPRESSION_TYPE_UNSPECIFIED = 'COMPRESSION_TYPE_UNSPECIFIED'
    RAW = 'RAW'
    RICE = 'RICE'


class GoogleSecuritySafebrowsingV4ThreatEntrySet(BaseModel):
    compressionType: Optional[CompressionType] = Field(
        None, description='The compression type for the entries in this set.'
    )
    rawHashes: Optional[GoogleSecuritySafebrowsingV4RawHashes] = Field(
        None, description='The raw SHA256-formatted entries.'
    )
    rawIndices: Optional[GoogleSecuritySafebrowsingV4RawIndices] = Field(
        None, description='The raw removal indices for a local list.'
    )
    riceHashes: Optional[GoogleSecuritySafebrowsingV4RiceDeltaEncoding] = Field(
        None,
        description='The encoded 4-byte prefixes of SHA256-formatted entries, using a Golomb-Rice encoding. The hashes are converted to uint32, sorted in ascending order, then delta encoded and stored as encoded_data.',
    )
    riceIndices: Optional[GoogleSecuritySafebrowsingV4RiceDeltaEncoding] = Field(
        None,
        description='The encoded local, lexicographically-sorted list indices, using a Golomb-Rice encoding. Used for sending compressed removal indices. The removal indices (uint32) are sorted in ascending order, then delta encoded and stored as encoded_data.',
    )


class Type(Enum):
    THREAT_SOURCE_TYPE_UNSPECIFIED = 'THREAT_SOURCE_TYPE_UNSPECIFIED'
    MATCHING_URL = 'MATCHING_URL'
    TAB_URL = 'TAB_URL'
    TAB_REDIRECT = 'TAB_REDIRECT'
    TAB_RESOURCE = 'TAB_RESOURCE'


class GoogleSecuritySafebrowsingV4ThreatHitThreatSource(BaseModel):
    referrer: Optional[str] = Field(
        None,
        description='Referrer of the resource. Only set if the referrer is available.',
    )
    remoteIp: Optional[str] = Field(
        None,
        description='The remote IP of the resource in ASCII format. Either IPv4 or IPv6.',
    )
    type: Optional[Type] = Field(None, description='The type of source reported.')
    url: Optional[str] = Field(None, description='The URL of the resource.')


class GoogleSecuritySafebrowsingV4ThreatHitUserInfo(BaseModel):
    regionCode: Optional[str] = Field(
        None, description="The UN M.49 region code associated with the user's location."
    )
    userId: Optional[str] = Field(
        None, description='Unique user identifier defined by the client.'
    )


class GoogleSecuritySafebrowsingV4ThreatInfo(BaseModel):
    platformTypes: Optional[List[PlatformType]] = Field(
        None, description='The platform types to be checked.'
    )
    threatEntries: Optional[List[GoogleSecuritySafebrowsingV4ThreatEntry]] = Field(
        None, description='The threat entries to be checked.'
    )
    threatEntryTypes: Optional[List[ThreatEntryType]] = Field(
        None, description='The entry types to be checked.'
    )
    threatTypes: Optional[List[ThreatType]] = Field(
        None, description='The threat types to be checked.'
    )


class GoogleSecuritySafebrowsingV4ThreatListDescriptor(BaseModel):
    platformType: Optional[PlatformType] = Field(
        None, description="The platform type targeted by the list's entries."
    )
    threatEntryType: Optional[ThreatEntryType] = Field(
        None, description='The entry types contained in the list.'
    )
    threatType: Optional[ThreatType] = Field(
        None, description="The threat type posed by the list's entries."
    )


class FieldXgafv(Enum):
    field_1 = '1'
    field_2 = '2'


class Alt(Enum):
    json = 'json'
    media = 'media'
    proto = 'proto'


class GoogleSecuritySafebrowsingV4FetchThreatListUpdatesRequestListUpdateRequest(
    BaseModel
):
    constraints: Optional[
        GoogleSecuritySafebrowsingV4FetchThreatListUpdatesRequestListUpdateRequestConstraints
    ] = Field(None, description='The constraints associated with this request.')
    platformType: Optional[PlatformType] = Field(
        None, description='The type of platform at risk by entries present in the list.'
    )
    state: Optional[str] = Field(
        None,
        description='The current state of the client for the requested list (the encrypted client state that was received from the last successful list update).',
    )
    threatEntryType: Optional[ThreatEntryType] = Field(
        None, description='The types of entries present in the list.'
    )
    threatType: Optional[ThreatType] = Field(
        None, description='The type of threat posed by entries present in the list.'
    )


class GoogleSecuritySafebrowsingV4FetchThreatListUpdatesResponseListUpdateResponse(
    BaseModel
):
    additions: Optional[List[GoogleSecuritySafebrowsingV4ThreatEntrySet]] = Field(
        None,
        description="A set of entries to add to a local threat type's list. Repeated to allow for a combination of compressed and raw data to be sent in a single response.",
    )
    checksum: Optional[GoogleSecuritySafebrowsingV4Checksum] = Field(
        None,
        description="The expected SHA256 hash of the client state; that is, of the sorted list of all hashes present in the database after applying the provided update. If the client state doesn't match the expected state, the client must disregard this update and retry later.",
    )
    newClientState: Optional[str] = Field(
        None,
        description='The new client state, in encrypted format. Opaque to clients.',
    )
    platformType: Optional[PlatformType] = Field(
        None, description='The platform type for which data is returned.'
    )
    removals: Optional[List[GoogleSecuritySafebrowsingV4ThreatEntrySet]] = Field(
        None,
        description="A set of entries to remove from a local threat type's list. In practice, this field is empty or contains exactly one ThreatEntrySet.",
    )
    responseType: Optional[ResponseType] = Field(
        None,
        description='The type of response. This may indicate that an action is required by the client when the response is received.',
    )
    threatEntryType: Optional[ThreatEntryType] = Field(
        None, description='The format of the threats.'
    )
    threatType: Optional[ThreatType] = Field(
        None, description='The threat type for which data is returned.'
    )


class GoogleSecuritySafebrowsingV4FindFullHashesRequest(BaseModel):
    apiClient: Optional[GoogleSecuritySafebrowsingV4ClientInfo] = Field(
        None,
        description="Client metadata associated with callers of higher-level APIs built on top of the client's implementation.",
    )
    client: Optional[GoogleSecuritySafebrowsingV4ClientInfo] = Field(
        None, description='The client metadata.'
    )
    clientStates: Optional[List[str]] = Field(
        None,
        description="The current client states for each of the client's local threat lists.",
    )
    threatInfo: Optional[GoogleSecuritySafebrowsingV4ThreatInfo] = Field(
        None, description='The lists and hashes to be checked.'
    )


class GoogleSecuritySafebrowsingV4FindThreatMatchesRequest(BaseModel):
    client: Optional[GoogleSecuritySafebrowsingV4ClientInfo] = Field(
        None, description='The client metadata.'
    )
    threatInfo: Optional[GoogleSecuritySafebrowsingV4ThreatInfo] = Field(
        None, description='The lists and entries to be checked for matches.'
    )


class GoogleSecuritySafebrowsingV4ListThreatListsResponse(BaseModel):
    threatLists: Optional[List[GoogleSecuritySafebrowsingV4ThreatListDescriptor]] = (
        Field(None, description='The lists available for download by the client.')
    )


class GoogleSecuritySafebrowsingV4ThreatEntryMetadata(BaseModel):
    entries: Optional[
        List[GoogleSecuritySafebrowsingV4ThreatEntryMetadataMetadataEntry]
    ] = Field(None, description='The metadata entries.')


class GoogleSecuritySafebrowsingV4ThreatHit(BaseModel):
    clientInfo: Optional[GoogleSecuritySafebrowsingV4ClientInfo] = Field(
        None, description='Client-reported identification.'
    )
    entry: Optional[GoogleSecuritySafebrowsingV4ThreatEntry] = Field(
        None,
        description='The threat entry responsible for the hit. Full hash should be reported for hash-based hits.',
    )
    platformType: Optional[PlatformType] = Field(
        None, description='The platform type reported.'
    )
    resources: Optional[List[GoogleSecuritySafebrowsingV4ThreatHitThreatSource]] = (
        Field(None, description='The resources related to the threat hit.')
    )
    threatType: Optional[ThreatType] = Field(
        None, description='The threat type reported.'
    )
    userInfo: Optional[GoogleSecuritySafebrowsingV4ThreatHitUserInfo] = Field(
        None, description='Details about the user that encountered the threat.'
    )


class GoogleSecuritySafebrowsingV4ThreatMatch(BaseModel):
    cacheDuration: Optional[str] = Field(
        None,
        description='The cache lifetime for the returned match. Clients must not cache this response for more than this duration to avoid false positives.',
    )
    platformType: Optional[PlatformType] = Field(
        None, description='The platform type matching this threat.'
    )
    threat: Optional[GoogleSecuritySafebrowsingV4ThreatEntry] = Field(
        None, description='The threat matching this threat.'
    )
    threatEntryMetadata: Optional[GoogleSecuritySafebrowsingV4ThreatEntryMetadata] = (
        Field(None, description='Optional metadata associated with this threat.')
    )
    threatEntryType: Optional[ThreatEntryType] = Field(
        None, description='The threat entry type matching this threat.'
    )
    threatType: Optional[ThreatType] = Field(
        None, description='The threat type matching this threat.'
    )


class GoogleSecuritySafebrowsingV4FetchThreatListUpdatesRequest(BaseModel):
    client: Optional[GoogleSecuritySafebrowsingV4ClientInfo] = Field(
        None, description='The client metadata.'
    )
    listUpdateRequests: Optional[
        List[GoogleSecuritySafebrowsingV4FetchThreatListUpdatesRequestListUpdateRequest]
    ] = Field(None, description='The requested threat list updates.')


class GoogleSecuritySafebrowsingV4FetchThreatListUpdatesResponse(BaseModel):
    listUpdateResponses: Optional[
        List[
            GoogleSecuritySafebrowsingV4FetchThreatListUpdatesResponseListUpdateResponse
        ]
    ] = Field(
        None,
        description='The list updates requested by the clients. The number of responses here may be less than the number of requests sent by clients. This is the case, for example, if the server has no updates for a particular list.',
    )
    minimumWaitDuration: Optional[str] = Field(
        None,
        description='The minimum duration the client must wait before issuing any update request. If this field is not set clients may update as soon as they want.',
    )


class GoogleSecuritySafebrowsingV4FindFullHashesResponse(BaseModel):
    matches: Optional[List[GoogleSecuritySafebrowsingV4ThreatMatch]] = Field(
        None, description='The full hashes that matched the requested prefixes.'
    )
    minimumWaitDuration: Optional[str] = Field(
        None,
        description='The minimum duration the client must wait before issuing any find hashes request. If this field is not set, clients can issue a request as soon as they want.',
    )
    negativeCacheDuration: Optional[str] = Field(
        None,
        description='For requested entities that did not match the threat list, how long to cache the response.',
    )


class GoogleSecuritySafebrowsingV4FindThreatMatchesResponse(BaseModel):
    matches: Optional[List[GoogleSecuritySafebrowsingV4ThreatMatch]] = Field(
        None, description='The threat list matches.'
    )
